/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Diseño;

import Logica.Condicion;
import Logica.Hipotesis;
import java.awt.*;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Viviana A
 */
public class Inicio extends javax.swing.JFrame {

    public static int rgl;
    public static String Lista[] = new String[20];//Vector para mostrar lista de hipotesis
    public static String Condicion[] = new String[20];//Vector para mostrar lista de condiciones
    int count;
    Icon Chulito;
    Icon Alerta;
    DefaultListModel modelo;
    DefaultListModel modelo1;
    
    public Inicio() {
        initComponents();
        this.setLocationRelativeTo(null);
        SuperiorReglasCondiciones.setVisible(true);
        CentralReglasCondiciones.setVisible(true);
        rgl = 0;
        txt_no.setEditable(false);
        txt_no.setText(String.valueOf(Inicio.rgl+1));
        Chulito = new ImageIcon("src/Imagenes/Chulito.png");    
        Alerta = new ImageIcon("src/Imagenes/Advertencia.png");
        modelo = new DefaultListModel();
        modelo1 = new DefaultListModel();
        JListOM.setSelectedIndex(0);
        JlistOL.setSelectedIndex(0);
        count=0;
    }

         //variables captura de hipotesis y conclusiones
            String atr;
            String val;
            String des;    
            String reg; 
            String atr_cond;
            String val_cond;
            String des_cond;
            String ope_cond;

             
             
      public String Hipotesis[]=new String[3];//Aqui se guardaran las hipotesis             
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        CentralReglasCondiciones = new javax.swing.JPanel();
        jpCondiciones = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        LstCondiciones = new javax.swing.JList<>();
        jpHipotesis = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        LstHipotesis = new javax.swing.JList<>();
        jSeparator1 = new javax.swing.JSeparator();
        btn_Actualizar = new javax.swing.JButton();
        txt_atr = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_val = new javax.swing.JTextField();
        txt_des = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_no = new javax.swing.JTextField();
        btn_agregarhipo1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JListOM = new javax.swing.JList<>();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JlistOL = new javax.swing.JList<>();
        btn_agregar = new javax.swing.JButton();
        txt_desc = new javax.swing.JTextField();
        txt_val1 = new javax.swing.JTextField();
        txt_atr1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btn_Actualizar1 = new javax.swing.JButton();
        Mov = new javax.swing.JLabel();
        minMI = new javax.swing.JLabel();
        CerrarMI = new javax.swing.JLabel();
        SuperiorReglasCondiciones = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jlbReglas1 = new javax.swing.JLabel();
        jlbInfAtras1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        PanelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        PanelPrincipal.setMinimumSize(new java.awt.Dimension(800, 600));
        PanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CentralReglasCondiciones.setBackground(new java.awt.Color(255, 255, 255));

        jpCondiciones.setBackground(new java.awt.Color(255, 255, 255));
        jpCondiciones.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CONDICIONES", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ebrima", 1, 12))); // NOI18N

        LstCondiciones.setFont(new java.awt.Font("Noto Sans", 1, 10)); // NOI18N
        jScrollPane6.setViewportView(LstCondiciones);

        javax.swing.GroupLayout jpCondicionesLayout = new javax.swing.GroupLayout(jpCondiciones);
        jpCondiciones.setLayout(jpCondicionesLayout);
        jpCondicionesLayout.setHorizontalGroup(
            jpCondicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCondicionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpCondicionesLayout.setVerticalGroup(
            jpCondicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCondicionesLayout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        jpHipotesis.setBackground(new java.awt.Color(255, 255, 255));
        jpHipotesis.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "HIPOTESIS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ebrima", 1, 12))); // NOI18N

        LstHipotesis.setFont(new java.awt.Font("Noto Sans", 1, 10)); // NOI18N
        jScrollPane5.setViewportView(LstHipotesis);

        javax.swing.GroupLayout jpHipotesisLayout = new javax.swing.GroupLayout(jpHipotesis);
        jpHipotesis.setLayout(jpHipotesisLayout);
        jpHipotesisLayout.setHorizontalGroup(
            jpHipotesisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpHipotesisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jpHipotesisLayout.setVerticalGroup(
            jpHipotesisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpHipotesisLayout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        btn_Actualizar.setBackground(new java.awt.Color(255, 255, 255));
        btn_Actualizar.setFont(new java.awt.Font("Noto Sans", 1, 10)); // NOI18N
        btn_Actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FlechaAdelante.png"))); // NOI18N
        btn_Actualizar.setText("Inferir Hacia Adelante");
        btn_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ActualizarActionPerformed(evt);
            }
        });

        txt_atr.setFont(new java.awt.Font("Noto Sans", 1, 11)); // NOI18N
        txt_atr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_atrActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Noto Sans", 1, 11)); // NOI18N
        jLabel5.setText("Atributo:");

        jLabel6.setFont(new java.awt.Font("Noto Sans", 1, 11)); // NOI18N
        jLabel6.setText("Valor:");

        txt_val.setFont(new java.awt.Font("Noto Sans", 1, 11)); // NOI18N
        txt_val.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_valActionPerformed(evt);
            }
        });

        txt_des.setFont(new java.awt.Font("Noto Sans", 1, 11)); // NOI18N
        txt_des.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_desActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Noto Sans", 1, 11)); // NOI18N
        jLabel7.setText("Descripción:");

        jLabel8.setFont(new java.awt.Font("Noto Sans", 1, 11)); // NOI18N
        jLabel8.setText("Regla No.");

        txt_no.setFont(new java.awt.Font("Noto Sans", 1, 11)); // NOI18N
        txt_no.setEnabled(false);
        txt_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_noActionPerformed(evt);
            }
        });

        btn_agregarhipo1.setFont(new java.awt.Font("Noto Sans", 1, 10)); // NOI18N
        btn_agregarhipo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Add.png"))); // NOI18N
        btn_agregarhipo1.setText("Agregar Regla");
        btn_agregarhipo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarhipo1ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Operador Matematico", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Noto Sans", 1, 11))); // NOI18N

        JListOM.setFont(new java.awt.Font("Noto Sans", 1, 11)); // NOI18N
        JListOM.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "=", "!=", "<", ">", "<=", ">=" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(JListOM);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Operador Logico", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Noto Sans", 1, 11))); // NOI18N

        JlistOL.setFont(new java.awt.Font("Noto Sans", 1, 11)); // NOI18N
        JlistOL.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Y", "O" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(JlistOL);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addContainerGap())
        );

        btn_agregar.setFont(new java.awt.Font("Noto Sans", 1, 10)); // NOI18N
        btn_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Add.png"))); // NOI18N
        btn_agregar.setText("Agregar Condición");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        txt_desc.setFont(new java.awt.Font("Noto Sans", 1, 11)); // NOI18N
        txt_desc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_descActionPerformed(evt);
            }
        });

        txt_val1.setFont(new java.awt.Font("Noto Sans", 1, 11)); // NOI18N
        txt_val1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_val1ActionPerformed(evt);
            }
        });

        txt_atr1.setFont(new java.awt.Font("Noto Sans", 1, 11)); // NOI18N
        txt_atr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_atr1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Noto Sans", 1, 11)); // NOI18N
        jLabel9.setText("Atributo:");

        jLabel10.setFont(new java.awt.Font("Noto Sans", 1, 11)); // NOI18N
        jLabel10.setText("Valor:");

        jLabel11.setFont(new java.awt.Font("Noto Sans", 1, 11)); // NOI18N
        jLabel11.setText("Descripcion");

        btn_Actualizar1.setBackground(new java.awt.Color(255, 255, 255));
        btn_Actualizar1.setFont(new java.awt.Font("Noto Sans", 1, 10)); // NOI18N
        btn_Actualizar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FlechaAtras.png"))); // NOI18N
        btn_Actualizar1.setText("Inferir Hacia Atras");
        btn_Actualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Actualizar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CentralReglasCondicionesLayout = new javax.swing.GroupLayout(CentralReglasCondiciones);
        CentralReglasCondiciones.setLayout(CentralReglasCondicionesLayout);
        CentralReglasCondicionesLayout.setHorizontalGroup(
            CentralReglasCondicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CentralReglasCondicionesLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(CentralReglasCondicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CentralReglasCondicionesLayout.createSequentialGroup()
                        .addComponent(jpCondiciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(CentralReglasCondicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CentralReglasCondicionesLayout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(CentralReglasCondicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(CentralReglasCondicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(CentralReglasCondicionesLayout.createSequentialGroup()
                                        .addComponent(txt_atr, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(67, 67, 67)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_no, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txt_val, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_des, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(CentralReglasCondicionesLayout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(CentralReglasCondicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(CentralReglasCondicionesLayout.createSequentialGroup()
                                        .addGroup(CentralReglasCondicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel11))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(CentralReglasCondicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_atr1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_val1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(btn_agregar))
                                .addGap(32, 32, 32)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49))))
                    .addGroup(CentralReglasCondicionesLayout.createSequentialGroup()
                        .addGroup(CentralReglasCondicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CentralReglasCondicionesLayout.createSequentialGroup()
                                .addComponent(jpHipotesis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(144, 144, 144)
                                .addComponent(btn_agregarhipo1))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(CentralReglasCondicionesLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(btn_Actualizar)
                                .addGap(43, 43, 43)
                                .addComponent(btn_Actualizar1)))
                        .addContainerGap())))
        );
        CentralReglasCondicionesLayout.setVerticalGroup(
            CentralReglasCondicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CentralReglasCondicionesLayout.createSequentialGroup()
                .addGroup(CentralReglasCondicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CentralReglasCondicionesLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(CentralReglasCondicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_atr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(txt_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(CentralReglasCondicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_val, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(CentralReglasCondicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_des, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addComponent(btn_agregarhipo1))
                    .addGroup(CentralReglasCondicionesLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(CentralReglasCondicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Actualizar1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jpHipotesis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(CentralReglasCondicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CentralReglasCondicionesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpCondiciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CentralReglasCondicionesLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(CentralReglasCondicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CentralReglasCondicionesLayout.createSequentialGroup()
                                .addGroup(CentralReglasCondicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(txt_atr1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(CentralReglasCondicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(txt_val1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(CentralReglasCondicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(txt_desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(btn_agregar))
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        PanelPrincipal.add(CentralReglasCondiciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 870, 530));

        Mov.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        Mov.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MovMouseDragged(evt);
            }
        });
        Mov.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MovMousePressed(evt);
            }
        });
        PanelPrincipal.add(Mov, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 30));

        minMI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Minus Math _28px.png"))); // NOI18N
        minMI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minMIMouseClicked(evt);
            }
        });
        PanelPrincipal.add(minMI, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, 30, 30));

        CerrarMI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cerrar.png"))); // NOI18N
        CerrarMI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CerrarMIMousePressed(evt);
            }
        });
        PanelPrincipal.add(CerrarMI, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, 30, 30));

        SuperiorReglasCondiciones.setBackground(new java.awt.Color(72, 71, 71));

        jLabel2.setFont(new java.awt.Font("Ebrima", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(235, 235, 235));
        jLabel2.setText("Reglas Y Condiciones");

        jlbReglas1.setBackground(new java.awt.Color(0, 0, 0));
        jlbReglas1.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jlbReglas1.setForeground(new java.awt.Color(235, 235, 235));
        jlbReglas1.setText("Universidad Distrital Francisco");

        jlbInfAtras1.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jlbInfAtras1.setForeground(new java.awt.Color(235, 235, 235));
        jlbInfAtras1.setText("Jose de Caldas");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/200px-Escudo_UD.svg.png"))); // NOI18N

        javax.swing.GroupLayout SuperiorReglasCondicionesLayout = new javax.swing.GroupLayout(SuperiorReglasCondiciones);
        SuperiorReglasCondiciones.setLayout(SuperiorReglasCondicionesLayout);
        SuperiorReglasCondicionesLayout.setHorizontalGroup(
            SuperiorReglasCondicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SuperiorReglasCondicionesLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 369, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGroup(SuperiorReglasCondicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbReglas1)
                    .addGroup(SuperiorReglasCondicionesLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jlbInfAtras1)))
                .addGap(20, 20, 20))
        );
        SuperiorReglasCondicionesLayout.setVerticalGroup(
            SuperiorReglasCondicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SuperiorReglasCondicionesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(SuperiorReglasCondicionesLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(SuperiorReglasCondicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(SuperiorReglasCondicionesLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jlbReglas1)
                        .addGap(3, 3, 3)
                        .addComponent(jlbInfAtras1)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        PanelPrincipal.add(SuperiorReglasCondiciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 960, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 955, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
        int xy;
        int xx;
        int x;
        int y;
        
    private void MovMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MovMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_MovMouseDragged

    private void MovMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MovMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_MovMousePressed

    private void minMIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMIMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_minMIMouseClicked

    private void CerrarMIMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarMIMousePressed
        Icon Salir = new ImageIcon("src/Imagenes/Salir.png");
        int resp=JOptionPane.showConfirmDialog(this, "¿Esta seguro de que desea salir?", "Confirmar",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, Salir);
        if(resp==JOptionPane.YES_OPTION){
            System.exit(0);            
        }
    }//GEN-LAST:event_CerrarMIMousePressed
    private DefaultListModel ModeloH()
    {
        DefaultListModel<String> model = new DefaultListModel<>();
        model.addElement( "Hola" );
        return model;
    }        
    private DefaultListModel ModeloC()
    {
        DefaultListModel<String> model = new DefaultListModel<>();
        model.addElement( "Mundo" );
        return model;
    }        
    private void btn_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ActualizarActionPerformed
//        LstHipotesis.setModel(ModeloH());
  //      LstCondiciones.setModel(ModeloC());
//    JOptionPane.showMessageDialog(Menu, LstHipotesis.getSelectedValue());
ArrayList AC= new ArrayList();    

Hipotesis H=new Hipotesis();
  H.setAtributo("Sol");
  H.setValor(1);
  H.setDescripcion("Mañana hará sol");
  H.setRegla(1);
  
  Hipotesis H2=new Hipotesis();
  H2.setAtributo("Lluvia");
  H2.setValor(1);
  H2.setDescripcion("Mañana lloverá");
  H2.setRegla(2);
  
  Condicion C=new Condicion();
  C.setAtributo("SolHoy");
  C.setValor(1);
  C.setDescripcion("Hoy hizo sol");
  C.setHi(H);
  
  AC.add(C);
  Condicion C2=new Condicion();
  C2.setAtributo("SolAyer");
  C2.setValor(1);
  C2.setDescripcion("Ayer hizo sol");
  C2.setHi(H);
  AC.add(C2);
  
  Condicion C3=new Condicion();
  C3.setAtributo("LluviaHoy");
  C3.setValor(1);
  C3.setDescripcion("Hoy llovio");
  C3.setHi(H2);
  AC.add(C3);
  
  Condicion C4=new Condicion();
  C4.setAtributo("LluviaAyer");
  C4.setValor(1);
  C4.setDescripcion("Ayer llovió");
  C4.setHi(H2);
  AC.add(C4);
  
  InferirHaciaAdelante(AC);
    }//GEN-LAST:event_btn_ActualizarActionPerformed
private void InferirHaciaAdelante(ArrayList AR)
{
    //JOptionPane.showMessageDialog(Menu, Hipo.getDescripcion());
    //Comienza a preguntar
    JOptionPane.showMessageDialog(this, "Comienza a preguntar para inferir");
    String rta[]=new String[AR.size()];
    int LastRule=0;
    int FC[]=new int[AR.size()];
    for(int i=0;i<AR.size();i++)
    {
        
        String VC[]=AR.get(i).toString().split("-");
        rta[i]=JOptionPane.showInputDialog("Pregunta "+(i+1)+"\n"+VC[2]);
                        
        if(rta[i].equals(VC[1]))
        {
            JOptionPane.showMessageDialog(this, "Contestaste verdadero H:"+VC[3]);
            FC[Integer.parseInt(VC[3])]++;
            //JOptionPane.showMessageDialog(Menu, FC[Integer.parseInt(VC[3])]);
        }else
        {
            JOptionPane.showMessageDialog(this, "Contestaste Falso H:"+VC[3]);
            FC[Integer.parseInt(VC[3])]--;
            //JOptionPane.showMessageDialog(Menu, FC[Integer.parseInt(VC[3])]);
        }
        LastRule=Integer.parseInt(VC[3]);
    }
    //int Respuesta=FC/AR.size();
    for(int i=1;i<LastRule+1;i++)
    {
        int Respuesta=FC[i]/LastRule;
        if(Respuesta==0)
    {
        JOptionPane.showMessageDialog(this, "Para la Hipotesis con regla "+(i)+" La respuesta es: Equiprobable, Factor de certeza=50% FC="+FC[i]);
        }else{
        if(Respuesta>0)
        JOptionPane.showMessageDialog(this, "Para la Hipotesis con regla "+(i)+" La respuesta es: Verdadero, Factor de certeza="+Respuesta*100+"% FC="+FC[i]);
        else
        JOptionPane.showMessageDialog(this, "Para la Hipotesis con regla "+(i)+" La respuesta es: Falso, Factor de certeza="+Respuesta*-100+"% FC="+FC[i]);
        }
    }
    
    /*if(rta[0].equals(rta[1]) && rta[0].equals("1"))
    {
        JOptionPane.showMessageDialog(Menu, Hipo.getDescripcion()+" Verdadero");
    }else
    {
        JOptionPane.showMessageDialog(Menu, Hipo.getDescripcion()+" Falso");
    }*/
}
        
    private void txt_atrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_atrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_atrActionPerformed

    private void txt_valActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_valActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_valActionPerformed

    private void txt_desActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_desActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_desActionPerformed

    private void txt_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_noActionPerformed

    private void btn_agregarhipo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarhipo1ActionPerformed
        if (txt_atr.getText().length()==0 || txt_val.getText().length()==0 || txt_des.getText().length()==0 || txt_no.getText().length()==0){
            JOptionPane.showMessageDialog(this, "Revise que haya ingresado todos los datos requeridos", "  Información",HEIGHT, Alerta);
        } else {

            atr = this.txt_atr.getText();
            val = this.txt_val.getText();
            des = this.txt_des.getText();
            reg = this.txt_no.getText();

            Hipotesis[0]=atr;
            Hipotesis[1]=val;
            Hipotesis[2]=des;

            String elem = (reg+". "+atr+" = "+val+"\n");
            Inicio.Lista[Integer.parseInt(reg)-1] = elem;

            for (int i=0; i<=(Integer.parseInt(reg)-1); i++){
                modelo.addElement(Inicio.Lista[i]);
            }

            Inicio.LstHipotesis.setModel(modelo);
            JOptionPane.showMessageDialog(this, "Hipotesis Registrada", "  Información",HEIGHT, Chulito);
            //this.dispose();
        }
    }//GEN-LAST:event_btn_agregarhipo1ActionPerformed

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        if (txt_atr.getText().length()==0 || txt_val.getText().length()==0 || txt_desc.getText().length()==0){
            JOptionPane.showMessageDialog(this, "Revise que haya ingresado todos los datos requeridos", "  Información",HEIGHT, Alerta);
        } else {
        
        atr_cond = this.txt_atr1.getText();
        val_cond = this.txt_val1.getText();
        des_cond = this.txt_desc1.getText();  
        ope_cond = JListOM.getSelectedValue();
        
        String elem = (atr+" "+ope_cond+" "+val);
        Condicion[count] = elem;
        
        for (int i=0; i<=(count); i++){
            modelo1.addElement(Condicion[i]);
            count=+1;
        }
        
        LstCondiciones.setModel(modelo1);
        JOptionPane.showMessageDialog(this, "Condición Registrada", "  Información",HEIGHT, Chulito); 
        }
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void txt_descActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_descActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_descActionPerformed

    private void txt_val1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_val1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_val1ActionPerformed

    private void txt_atr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_atr1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_atr1ActionPerformed

    private void btn_Actualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Actualizar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Actualizar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CentralReglasCondiciones;
    private javax.swing.JLabel CerrarMI;
    private javax.swing.JList<String> JListOM;
    private javax.swing.JList<String> JlistOL;
    private javax.swing.JList<String> LstCondiciones;
    public static javax.swing.JList<String> LstHipotesis;
    private javax.swing.JLabel Mov;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JPanel SuperiorReglasCondiciones;
    private javax.swing.JButton btn_Actualizar;
    private javax.swing.JButton btn_Actualizar1;
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_agregarhipo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jlbInfAtras1;
    private javax.swing.JLabel jlbReglas1;
    private javax.swing.JPanel jpCondiciones;
    private javax.swing.JPanel jpHipotesis;
    private javax.swing.JLabel minMI;
    private javax.swing.JTextField txt_atr;
    private javax.swing.JTextField txt_atr1;
    private javax.swing.JTextField txt_des;
    private javax.swing.JTextField txt_desc;
    private javax.swing.JTextField txt_no;
    private javax.swing.JTextField txt_val;
    private javax.swing.JTextField txt_val1;
    // End of variables declaration//GEN-END:variables
}
