/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Diseño;

import java.awt.*;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Viviana A
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        this.setLocationRelativeTo(null);
        limpiarPaneles();
        setColor(btn_Reglas);
        SuperiorReglasCondiciones.setVisible(true);
        CentralReglasCondiciones.setVisible(true);
        //txtHipotesis.setEditable(false);
        //txtCondiciones.setEditable(false);
        txtInferirAtras.setEditable(false);
        txtInferirAdelante.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        btn_Reglas = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jlbReglas = new javax.swing.JLabel();
        btn_InferirAd = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jlbInfAdelante = new javax.swing.JLabel();
        btn_InferirAt = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jlbInfAtras = new javax.swing.JLabel();
        jlbReglas1 = new javax.swing.JLabel();
        jlbInfAtras1 = new javax.swing.JLabel();
        jlbReglas2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Mov = new javax.swing.JLabel();
        minMI = new javax.swing.JLabel();
        CerrarMI = new javax.swing.JLabel();
        SuperiorReglasCondiciones = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        SuperiorInferirAdelante = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        SuperiorInferirAtras = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        CentralReglasCondiciones = new javax.swing.JPanel();
        jpCondiciones = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        LstCondiciones = new javax.swing.JList<>();
        jpHipotesis = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        LstHipotesis = new javax.swing.JList<>();
        btn_EliminarHipo = new javax.swing.JButton();
        btn_AgregarCond = new javax.swing.JButton();
        btn_EliminarCond = new javax.swing.JButton();
        btn_AgregarHipo = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btn_Actualizar = new javax.swing.JButton();
        CentralInferirAtras = new javax.swing.JPanel();
        PanelInfAtras = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtInferirAtras = new javax.swing.JTextArea();
        btn_InferirAtras = new javax.swing.JButton();
        CentralInferirAdelante = new javax.swing.JPanel();
        PanelInfAd = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtInferirAdelante = new javax.swing.JTextArea();
        btn_InferirAdelante = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        PanelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        PanelPrincipal.setMinimumSize(new java.awt.Dimension(800, 600));
        PanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu.setBackground(new java.awt.Color(9, 28, 65));
        Menu.setToolTipText("");
        Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Reglas.setBackground(new java.awt.Color(14, 42, 97));
        btn_Reglas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Reglas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_ReglasMousePressed(evt);
            }
        });

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/+.png"))); // NOI18N

        jlbReglas.setFont(new java.awt.Font("Ebrima", 1, 13)); // NOI18N
        jlbReglas.setForeground(new java.awt.Color(235, 235, 235));
        jlbReglas.setText("Reglas Y Condiciones");

        javax.swing.GroupLayout btn_ReglasLayout = new javax.swing.GroupLayout(btn_Reglas);
        btn_Reglas.setLayout(btn_ReglasLayout);
        btn_ReglasLayout.setHorizontalGroup(
            btn_ReglasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_ReglasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlbReglas)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        btn_ReglasLayout.setVerticalGroup(
            btn_ReglasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(btn_ReglasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbReglas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Menu.add(btn_Reglas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 240, -1));

        btn_InferirAd.setBackground(new java.awt.Color(14, 42, 97));
        btn_InferirAd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_InferirAd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_InferirAdMousePressed(evt);
            }
        });

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Flecha_Adelante.png"))); // NOI18N

        jlbInfAdelante.setFont(new java.awt.Font("Ebrima", 1, 13)); // NOI18N
        jlbInfAdelante.setForeground(new java.awt.Color(235, 235, 235));
        jlbInfAdelante.setText("Inferir Hacia Adelante");
        jlbInfAdelante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbInfAdelanteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btn_InferirAdLayout = new javax.swing.GroupLayout(btn_InferirAd);
        btn_InferirAd.setLayout(btn_InferirAdLayout);
        btn_InferirAdLayout.setHorizontalGroup(
            btn_InferirAdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_InferirAdLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlbInfAdelante)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        btn_InferirAdLayout.setVerticalGroup(
            btn_InferirAdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_InferirAdLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbInfAdelante)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Menu.add(btn_InferirAd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 240, -1));

        btn_InferirAt.setBackground(new java.awt.Color(14, 42, 97));
        btn_InferirAt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_InferirAt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_InferirAtMousePressed(evt);
            }
        });

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Flecha_Atras.png"))); // NOI18N

        jlbInfAtras.setFont(new java.awt.Font("Ebrima", 1, 13)); // NOI18N
        jlbInfAtras.setForeground(new java.awt.Color(235, 235, 235));
        jlbInfAtras.setText("Inferir Hacia Atras");
        jlbInfAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbInfAtrasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btn_InferirAtLayout = new javax.swing.GroupLayout(btn_InferirAt);
        btn_InferirAt.setLayout(btn_InferirAtLayout);
        btn_InferirAtLayout.setHorizontalGroup(
            btn_InferirAtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_InferirAtLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlbInfAtras)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        btn_InferirAtLayout.setVerticalGroup(
            btn_InferirAtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(btn_InferirAtLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbInfAtras)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Menu.add(btn_InferirAt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 240, -1));

        jlbReglas1.setBackground(new java.awt.Color(0, 0, 0));
        jlbReglas1.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jlbReglas1.setForeground(new java.awt.Color(235, 235, 235));
        jlbReglas1.setText("Universidad Distrital Francisco");
        Menu.add(jlbReglas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 600, -1, -1));

        jlbInfAtras1.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jlbInfAtras1.setForeground(new java.awt.Color(235, 235, 235));
        jlbInfAtras1.setText("Jose de Caldas");
        Menu.add(jlbInfAtras1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 620, -1, -1));

        jlbReglas2.setFont(new java.awt.Font("Ebrima", 3, 16)); // NOI18N
        jlbReglas2.setForeground(new java.awt.Color(235, 235, 235));
        jlbReglas2.setText("MOTOR DE INFERENCIA");
        Menu.add(jlbReglas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/200px-Escudo_UD.svg.png"))); // NOI18N
        Menu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 60, 50));

        PanelPrincipal.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 780));

        Mov.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        Mov.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MovMouseDragged(evt);
            }
        });
        Mov.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MovMousePressed(evt);
            }
        });
        PanelPrincipal.add(Mov, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 0, 790, 30));

        minMI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Minus Math _28px.png"))); // NOI18N
        minMI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minMIMouseClicked(evt);
            }
        });
        PanelPrincipal.add(minMI, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 30, 30));

        CerrarMI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cerrar.png"))); // NOI18N
        CerrarMI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CerrarMIMousePressed(evt);
            }
        });
        PanelPrincipal.add(CerrarMI, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 0, 30, 30));

        SuperiorReglasCondiciones.setBackground(new java.awt.Color(72, 71, 71));

        jLabel2.setFont(new java.awt.Font("Ebrima", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(235, 235, 235));
        jLabel2.setText("Reglas Y Condiciones");

        javax.swing.GroupLayout SuperiorReglasCondicionesLayout = new javax.swing.GroupLayout(SuperiorReglasCondiciones);
        SuperiorReglasCondiciones.setLayout(SuperiorReglasCondicionesLayout);
        SuperiorReglasCondicionesLayout.setHorizontalGroup(
            SuperiorReglasCondicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SuperiorReglasCondicionesLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(497, Short.MAX_VALUE))
        );
        SuperiorReglasCondicionesLayout.setVerticalGroup(
            SuperiorReglasCondicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SuperiorReglasCondicionesLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        PanelPrincipal.add(SuperiorReglasCondiciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 830, -1));

        SuperiorInferirAdelante.setBackground(new java.awt.Color(72, 71, 71));

        jLabel3.setFont(new java.awt.Font("Ebrima", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(235, 235, 235));
        jLabel3.setText("Inferencia Hacia Adelante");

        javax.swing.GroupLayout SuperiorInferirAdelanteLayout = new javax.swing.GroupLayout(SuperiorInferirAdelante);
        SuperiorInferirAdelante.setLayout(SuperiorInferirAdelanteLayout);
        SuperiorInferirAdelanteLayout.setHorizontalGroup(
            SuperiorInferirAdelanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SuperiorInferirAdelanteLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(497, Short.MAX_VALUE))
        );
        SuperiorInferirAdelanteLayout.setVerticalGroup(
            SuperiorInferirAdelanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SuperiorInferirAdelanteLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        PanelPrincipal.add(SuperiorInferirAdelante, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 830, -1));

        SuperiorInferirAtras.setBackground(new java.awt.Color(72, 71, 71));

        jLabel4.setFont(new java.awt.Font("Ebrima", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(235, 235, 235));
        jLabel4.setText("Inferencia Hacia Atras");

        javax.swing.GroupLayout SuperiorInferirAtrasLayout = new javax.swing.GroupLayout(SuperiorInferirAtras);
        SuperiorInferirAtras.setLayout(SuperiorInferirAtrasLayout);
        SuperiorInferirAtrasLayout.setHorizontalGroup(
            SuperiorInferirAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SuperiorInferirAtrasLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(497, Short.MAX_VALUE))
        );
        SuperiorInferirAtrasLayout.setVerticalGroup(
            SuperiorInferirAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SuperiorInferirAtrasLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        PanelPrincipal.add(SuperiorInferirAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 830, -1));

        CentralReglasCondiciones.setBackground(new java.awt.Color(255, 255, 255));

        jpCondiciones.setBackground(new java.awt.Color(255, 255, 255));
        jpCondiciones.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CONDICIONES", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ebrima", 1, 12))); // NOI18N

        LstCondiciones.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane6.setViewportView(LstCondiciones);

        javax.swing.GroupLayout jpCondicionesLayout = new javax.swing.GroupLayout(jpCondiciones);
        jpCondiciones.setLayout(jpCondicionesLayout);
        jpCondicionesLayout.setHorizontalGroup(
            jpCondicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCondicionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpCondicionesLayout.setVerticalGroup(
            jpCondicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
        );

        jpHipotesis.setBackground(new java.awt.Color(255, 255, 255));
        jpHipotesis.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "HIPOTESIS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ebrima", 1, 12))); // NOI18N

        LstHipotesis.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(LstHipotesis);

        javax.swing.GroupLayout jpHipotesisLayout = new javax.swing.GroupLayout(jpHipotesis);
        jpHipotesis.setLayout(jpHipotesisLayout);
        jpHipotesisLayout.setHorizontalGroup(
            jpHipotesisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpHipotesisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpHipotesisLayout.setVerticalGroup(
            jpHipotesisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
        );

        btn_EliminarHipo.setBackground(new java.awt.Color(255, 255, 255));
        btn_EliminarHipo.setFont(new java.awt.Font("Noto Sans", 1, 10)); // NOI18N
        btn_EliminarHipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Delete.png"))); // NOI18N
        btn_EliminarHipo.setText("Eliminar Hipótesis");
        btn_EliminarHipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EliminarHipoActionPerformed(evt);
            }
        });

        btn_AgregarCond.setBackground(new java.awt.Color(255, 255, 255));
        btn_AgregarCond.setFont(new java.awt.Font("Noto Sans", 1, 10)); // NOI18N
        btn_AgregarCond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Add.png"))); // NOI18N
        btn_AgregarCond.setText("Agregar Condición");
        btn_AgregarCond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AgregarCondActionPerformed(evt);
            }
        });

        btn_EliminarCond.setBackground(new java.awt.Color(255, 255, 255));
        btn_EliminarCond.setFont(new java.awt.Font("Noto Sans", 1, 10)); // NOI18N
        btn_EliminarCond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Delete.png"))); // NOI18N
        btn_EliminarCond.setText("Eliminar Condición");
        btn_EliminarCond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EliminarCondActionPerformed(evt);
            }
        });

        btn_AgregarHipo.setBackground(new java.awt.Color(255, 255, 255));
        btn_AgregarHipo.setFont(new java.awt.Font("Noto Sans", 1, 10)); // NOI18N
        btn_AgregarHipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Add.png"))); // NOI18N
        btn_AgregarHipo.setText("Agregar Hipótesis");
        btn_AgregarHipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AgregarHipoActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btn_Actualizar.setBackground(new java.awt.Color(255, 255, 255));
        btn_Actualizar.setFont(new java.awt.Font("Noto Sans", 1, 10)); // NOI18N
        btn_Actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/refrescar.png"))); // NOI18N
        btn_Actualizar.setText("Actualizar");
        btn_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CentralReglasCondicionesLayout = new javax.swing.GroupLayout(CentralReglasCondiciones);
        CentralReglasCondiciones.setLayout(CentralReglasCondicionesLayout);
        CentralReglasCondicionesLayout.setHorizontalGroup(
            CentralReglasCondicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CentralReglasCondicionesLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(CentralReglasCondicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Actualizar)
                    .addGroup(CentralReglasCondicionesLayout.createSequentialGroup()
                        .addGroup(CentralReglasCondicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpHipotesis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(CentralReglasCondicionesLayout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(CentralReglasCondicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_EliminarHipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_AgregarHipo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(37, 37, 37)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(CentralReglasCondicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CentralReglasCondicionesLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jpCondiciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CentralReglasCondicionesLayout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addGroup(CentralReglasCondicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_EliminarCond, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_AgregarCond, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        CentralReglasCondicionesLayout.setVerticalGroup(
            CentralReglasCondicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CentralReglasCondicionesLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btn_Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(CentralReglasCondicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CentralReglasCondicionesLayout.createSequentialGroup()
                        .addGroup(CentralReglasCondicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpHipotesis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpCondiciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(CentralReglasCondicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CentralReglasCondicionesLayout.createSequentialGroup()
                                .addComponent(btn_AgregarHipo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_EliminarHipo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CentralReglasCondicionesLayout.createSequentialGroup()
                                .addComponent(btn_AgregarCond, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_EliminarCond, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        PanelPrincipal.add(CentralReglasCondiciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 810, 530));

        CentralInferirAtras.setBackground(new java.awt.Color(255, 255, 255));

        PanelInfAtras.setBackground(new java.awt.Color(255, 255, 255));
        PanelInfAtras.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ESCOJA UNA HIPOTESIS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ebrima", 1, 12))); // NOI18N
        PanelInfAtras.setPreferredSize(new java.awt.Dimension(291, 355));

        txtInferirAtras.setColumns(20);
        txtInferirAtras.setRows(5);
        txtInferirAtras.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jScrollPane3.setViewportView(txtInferirAtras);

        javax.swing.GroupLayout PanelInfAtrasLayout = new javax.swing.GroupLayout(PanelInfAtras);
        PanelInfAtras.setLayout(PanelInfAtrasLayout);
        PanelInfAtrasLayout.setHorizontalGroup(
            PanelInfAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelInfAtrasLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PanelInfAtrasLayout.setVerticalGroup(
            PanelInfAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInfAtrasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_InferirAtras.setBackground(new java.awt.Color(255, 255, 255));
        btn_InferirAtras.setFont(new java.awt.Font("Noto Sans", 1, 10)); // NOI18N
        btn_InferirAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FlechaAtras.png"))); // NOI18N
        btn_InferirAtras.setText("Inferir Hacia Atras");
        btn_InferirAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_InferirAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CentralInferirAtrasLayout = new javax.swing.GroupLayout(CentralInferirAtras);
        CentralInferirAtras.setLayout(CentralInferirAtrasLayout);
        CentralInferirAtrasLayout.setHorizontalGroup(
            CentralInferirAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CentralInferirAtrasLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(CentralInferirAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelInfAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CentralInferirAtrasLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(btn_InferirAtras)))
                .addContainerGap(487, Short.MAX_VALUE))
        );
        CentralInferirAtrasLayout.setVerticalGroup(
            CentralInferirAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CentralInferirAtrasLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(PanelInfAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(btn_InferirAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        PanelPrincipal.add(CentralInferirAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 810, 510));

        CentralInferirAdelante.setBackground(new java.awt.Color(255, 255, 255));

        PanelInfAd.setBackground(new java.awt.Color(255, 255, 255));
        PanelInfAd.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BASE DE HECHOS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ebrima", 1, 12))); // NOI18N

        txtInferirAdelante.setColumns(20);
        txtInferirAdelante.setRows(5);
        txtInferirAdelante.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jScrollPane4.setViewportView(txtInferirAdelante);

        javax.swing.GroupLayout PanelInfAdLayout = new javax.swing.GroupLayout(PanelInfAd);
        PanelInfAd.setLayout(PanelInfAdLayout);
        PanelInfAdLayout.setHorizontalGroup(
            PanelInfAdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInfAdLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelInfAdLayout.setVerticalGroup(
            PanelInfAdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInfAdLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                .addContainerGap())
        );

        btn_InferirAdelante.setBackground(new java.awt.Color(255, 255, 255));
        btn_InferirAdelante.setFont(new java.awt.Font("Noto Sans", 1, 10)); // NOI18N
        btn_InferirAdelante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FlechaAtras.png"))); // NOI18N
        btn_InferirAdelante.setText("Inferir Hacia Adelante");
        btn_InferirAdelante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_InferirAdelanteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CentralInferirAdelanteLayout = new javax.swing.GroupLayout(CentralInferirAdelante);
        CentralInferirAdelante.setLayout(CentralInferirAdelanteLayout);
        CentralInferirAdelanteLayout.setHorizontalGroup(
            CentralInferirAdelanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CentralInferirAdelanteLayout.createSequentialGroup()
                .addGroup(CentralInferirAdelanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CentralInferirAdelanteLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(btn_InferirAdelante))
                    .addGroup(CentralInferirAdelanteLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(PanelInfAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(490, Short.MAX_VALUE))
        );
        CentralInferirAdelanteLayout.setVerticalGroup(
            CentralInferirAdelanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CentralInferirAdelanteLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(PanelInfAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_InferirAdelante, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelPrincipal.add(CentralInferirAdelante, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 810, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 1049, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ReglasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ReglasMousePressed
        limpiarPaneles();
        EnviarFocuGris(btn_Reglas);
        SuperiorReglasCondiciones.setVisible(true);
        CentralReglasCondiciones.setVisible(true);
    }//GEN-LAST:event_btn_ReglasMousePressed
   
    private void limpiarPaneles(){
        SuperiorReglasCondiciones.setVisible(false);
        SuperiorInferirAdelante.setVisible(false);
        SuperiorInferirAtras.setVisible(false);
        
        CentralReglasCondiciones.setVisible(false);
        CentralInferirAdelante.setVisible(false);
        CentralInferirAtras.setVisible(false);
    }
    
    private void EnviarFocuGris(JPanel S){
        resetColor(btn_Reglas);
        resetColor(btn_InferirAd);
        resetColor(btn_InferirAt);
        setColor(S);
    }
    
    void resetColor(JPanel panel){
        panel.setBackground(new Color(14,42,97));
    }
    
    void setColor(JPanel panel){
        panel.setBackground(new Color(25,77,179));
    }
    
    private void btn_InferirAdMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_InferirAdMousePressed
        limpiarPaneles();
        EnviarFocuGris(btn_InferirAd);
        SuperiorInferirAdelante.setVisible(true);
        CentralInferirAdelante.setVisible(true);        
    }//GEN-LAST:event_btn_InferirAdMousePressed

        int xy;
        int xx;
        int x;
        int y;
        
    private void btn_InferirAtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_InferirAtMousePressed
        limpiarPaneles();
        EnviarFocuGris(btn_InferirAt);
        SuperiorInferirAtras.setVisible(true);
        CentralInferirAtras.setVisible(true);       
    }//GEN-LAST:event_btn_InferirAtMousePressed

    private void MovMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MovMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_MovMouseDragged

    private void MovMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MovMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_MovMousePressed

    private void minMIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMIMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_minMIMouseClicked

    private void CerrarMIMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarMIMousePressed
        Icon Salir = new ImageIcon("src/Imagenes/Salir.png");
        int resp=JOptionPane.showConfirmDialog(this, "¿Esta seguro de que desea salir?", "Confirmar",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, Salir);
        if(resp==JOptionPane.YES_OPTION){
            System.exit(0);            
        }
    }//GEN-LAST:event_CerrarMIMousePressed

    private void btn_EliminarHipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EliminarHipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_EliminarHipoActionPerformed

    private void btn_AgregarCondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AgregarCondActionPerformed
        NuevaCondicion abrir = new NuevaCondicion();
       abrir.setVisible(true);   
    }//GEN-LAST:event_btn_AgregarCondActionPerformed

    private void btn_EliminarCondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EliminarCondActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_EliminarCondActionPerformed

    private void btn_AgregarHipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AgregarHipoActionPerformed
       NuevaHipotesis abrir = new NuevaHipotesis();
       abrir.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_AgregarHipoActionPerformed

    private void btn_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ActualizarActionPerformed

    private void btn_InferirAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_InferirAtrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_InferirAtrasActionPerformed

    private void btn_InferirAdelanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_InferirAdelanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_InferirAdelanteActionPerformed

    private void jlbInfAdelanteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbInfAdelanteMouseClicked
       /*Adelante abrir = new Adelante();
       abrir.setVisible(true);*/
    }//GEN-LAST:event_jlbInfAdelanteMouseClicked

    private void jlbInfAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbInfAtrasMouseClicked
       /* Atras abrir = new Atras();
       abrir.setVisible(true);*/
    }//GEN-LAST:event_jlbInfAtrasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CentralInferirAdelante;
    private javax.swing.JPanel CentralInferirAtras;
    private javax.swing.JPanel CentralReglasCondiciones;
    private javax.swing.JLabel CerrarMI;
    private javax.swing.JList<String> LstCondiciones;
    private javax.swing.JList<String> LstHipotesis;
    private javax.swing.JPanel Menu;
    private javax.swing.JLabel Mov;
    private javax.swing.JPanel PanelInfAd;
    private javax.swing.JPanel PanelInfAtras;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JPanel SuperiorInferirAdelante;
    private javax.swing.JPanel SuperiorInferirAtras;
    private javax.swing.JPanel SuperiorReglasCondiciones;
    private javax.swing.JButton btn_Actualizar;
    private javax.swing.JButton btn_AgregarCond;
    private javax.swing.JButton btn_AgregarHipo;
    private javax.swing.JButton btn_EliminarCond;
    private javax.swing.JButton btn_EliminarHipo;
    private javax.swing.JPanel btn_InferirAd;
    private javax.swing.JButton btn_InferirAdelante;
    private javax.swing.JPanel btn_InferirAt;
    private javax.swing.JButton btn_InferirAtras;
    private javax.swing.JPanel btn_Reglas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jlbInfAdelante;
    private javax.swing.JLabel jlbInfAtras;
    private javax.swing.JLabel jlbInfAtras1;
    private javax.swing.JLabel jlbReglas;
    private javax.swing.JLabel jlbReglas1;
    private javax.swing.JLabel jlbReglas2;
    private javax.swing.JPanel jpCondiciones;
    private javax.swing.JPanel jpHipotesis;
    private javax.swing.JLabel minMI;
    private javax.swing.JTextArea txtInferirAdelante;
    private javax.swing.JTextArea txtInferirAtras;
    // End of variables declaration//GEN-END:variables
}
